### ISSUE TITLE
allow skipping update of yum/openssl/python

### ISSUE THREAD

**Issue by evgeni** [Katello/katello-client-bootstrap#150]
some customers might want to skip it due to $reasons

**Comment by sideangleside** [comment]
I can imagine that customers would want this, Defaults should still be to update the packages

**Comment by evgeni** [comment]
see https://github.com/evgeni/katello-client-bootstrap/tree/modular-skip for a possible solution

**Comment by sideangleside** [comment]
Since we are giving the user the ability to arbitrarily skip steps (that usually are mandatory), I think we should also allow them to skip installation of the katello-agent. Some users choose not to deploy it (and are OK with the ramifications of doing such), and there is no reason why we should force them to.

**Comment by evgeni** [comment]
you mean like https://github.com/Katello/katello-client-bootstrap/pull/159/commits/cb5f0d4ae04578c733b75b15fee348c9b05c69dc in my PR? :-)

see #159

**Comment by sideangleside** [comment]
Yes 👍
