### ISSUE TITLE
Re-bootstrapping hosts with different --fqdn generates two hosts in satellite.

### ISSUE THREAD

**Issue by bergsjoh** [Katello/katello-client-bootstrap#180]
This is due to the check in generate_katello_facts() that doesn't write the file if it already exists;

-    if FQDN.find(".") != -1 and not os.path.exists('/etc/rhsm/facts/katello.facts'):
+    if FQDN.find(".") != -1:

fixes the problem, and will overwrite the file every time bootstrap runs.

**Comment by sideangleside** [comment]
What version of bootstrap are you running?  As part of #164, and specifically https://github.com/Katello/katello-client-bootstrap/pull/164/commits/3bb30bb2a337fc6f2155a98916a5220a58607dda, we unconditionally write `/etc/rhsm/facts/katello.facts`. (bootstrap has to effectively clobber whatever the `katello-ca-consumer` RPM provides so that we can support the arbitrary FQDN.)

Now that you have me thinking about this, It may make sense to update the `unregister_system`function such that when `--remove` is passed, we delete `/etc/rhsm/facts/katello.facts`

@evgeni: Thoughts?

**Comment by bergsjoh** [comment]
Whoops, sorry. I applied an old version of the generate_katello_facts() in my bootstrap yesterday.

I should look at the upstream code before submitting issues!

**Comment by evgeni** [comment]
I must admit I don't like fiddling around with files in /etc after there were initially created.

So *if* we do this, we should add some header to the file, saying it will vanish and people should use an own file...

**Comment by sideangleside** [comment]
Well, the file _is_ created:

- via `katello-ca-consumer` installation (in the %post section)
- via bootstrap.py

The RPM potentially _should_ own the file (and remove it on uninstall). Then we don't have to worry about removing it.
