### ISSUE TITLE
[RFE] Add option to move from one Satellite 6 to another or capsule

### ISSUE THREAD

**Issue by gearboxscott** [Katello/katello-client-bootstrap#181]
I know the script has legacy but how about adding functionality to move from one Satellite 6 to Another or a capsule?

**Comment by evgeni** [comment]
you can do this today already. you just have to call the script with `--force` so that it cleans up old registration data. see https://github.com/Katello/katello-client-bootstrap/blob/master/README.md#migrating-a-system-from-one-foreman--katello-installation-to-another

as for moving to another capsule of the *same* satellite: this is being worked on in https://github.com/Katello/katello-client-bootstrap/pull/168

**Comment by gearboxscott** [comment]
agreed and worked as designed.  Thanks.
