### ISSUE TITLE
bootstrap hangs if rhsmcertd hangs

### ISSUE THREAD

**Issue by evgeni** [Katello/katello-client-bootstrap#76]
situation similar to
https://access.redhat.com/solutions/1342823
https://access.redhat.com/solutions/1754373
https://access.redhat.com/solutions/2110281
https://access.redhat.com/solutions/2202931

should we bounce rhsmcertd before trying?

**Comment by sideangleside** [comment]
Do we still want to (have to) address this? In #147 we (re)start rhsmcertd _after_ the script is complete. Do we also want to restart it earlier in the script (basically immediately after we install/update subscription-manager)?

In some of those KCS articles you listed, rhsmcertd needed a `kill -9` in order to behave correct. I'd rather not have to do that.

**Comment by evgeni** [comment]
In the cases it hit me, "service rhsmcertd restart" was not sufficient. It would restart the main thread, but there would still be an old worker running, blocking all the stuff. `kill -9` was the only solution. But I agree that this is ugly.

**Comment by evgeni** [comment]
I think we should just start our subprocs with a timeout, and if that is reached, kill it and abort.

**Comment by evgeni** [comment]
there was an PR #83 that got closed with:
with [rhbz1346417](https://bugzilla.redhat.com/show_bug.cgi?id=1346417), subscription-manager now sets a timeout for SSL connections. This PR is no longer needed. (And since it hasn't been merged yet, I'm closing it out)

I tend to agree and close this one too
